### PR TITLE
Add shellcheck to fix common errors

### LINKED ISSUE #39: Add shellcheck to catch common errors
Configure travis to run shellcheck to catch common issues like the one highlighted in https://github.com/inviqa/harness-base-php/issues/36

Example can be seen at :- https://github.com/my127/workspace/blob/0.1.x/.travis.yml#L17

**AC**
- [x] shellcheck added to .travis.yml 
- [x] errors picked up by shellcechk are resolved

### PR DESCRIPTION
**Pull request by hgajjar**
Fixes #39

### CODE REVIEW

File: src/_base/harness/scripts/destroy.sh [hunk 1]
```diff
@@ -9,6 +9,7 @@ if [[ "$USE_DOCKER_SYNC" = "yes" ]]; then
 fi
 
 if [[ "$APP_BUILD" = "static" ]]; then
+    # shellcheck disable=SC2046
```
Comment (hgajjar) [inline src/_base/harness/scripts/destroy.sh:12]: As we are intentionally splitting the word here, I'm not sure if we can fix this shellcheck error.

**Review by coledave — APPROVED** [review]
